name: Test and Coverage

on:
  push:
    branches: [ main, develop, 'feature/*', 'fix/*', 'copilot/*' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    
    - name: Run unit tests with coverage
      run: |
        pytest tests/test_financial_calculator.py -v --cov=firefly --cov-report=term-missing --cov-report=xml --cov-fail-under=95

  quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black isort mypy
        pip install -e .
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 firefly --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 firefly --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
    
    - name: Check code formatting with black
      run: |
        black --check --diff firefly tests
    
    - name: Check import sorting with isort
      run: |
        isort --check-only --diff firefly tests
    
    - name: Type checking with mypy
      run: |
        mypy firefly --ignore-missing-imports

  acceptance:
    runs-on: ubuntu-latest
    needs: [test, quality]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    
    - name: Run BDD acceptance tests
      run: |
        pytest tests/test_future_value_bdd.py -v --tb=short